server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://livecommerce_database:3306/livecommerce?characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false # 도커 컨테이너 db 연결
    username: user
    password: 12345678!
  flyway:
    baseline-on-migrate: true

mybatis:
  type-aliases-package: com.flab.livecommerce.domain
  configuration:
    map-underscore-to-camel-case: true
