version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: livecommerce_elastic
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - elastic


  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: livecommerce_kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic


  apm:
    image: docker.elastic.co/apm/apm-server:7.15.0
    container_name: livecommerce_apm
    ports:
      - "8200:8200"
    environment:
      output.elasticsearch.hosts: '["elasticsearch:9200"]'

  db:
    container_name: livecommerce_database
    image: mysql:8.0.28
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"


networks:
  elastic:
    driver: bridge