version: '3.7'
services:
  db:
    container_name: livecommerce_database
    image: mysql:8.0.28
    restart: on-failure
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"